"""Autogenerated by Alembic - please adjust!"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlalchemy.dialects.postgresql as psql


def upgrade() -> None:
    pass


def downgrade() -> None:
    pass
